version: '3'
services:
  usersnjapp:
    build:
      dockerfile: Dockerfile
      context: ./usersnjappdkimg
    ports:
      - '3010:3005'
    environment:
      - PGDBDATABASE=usersapi
      - PGDBUSER=dbuser
      - PGDBPASSWORD=dbpassword
      - PGDBPORT=15432
      - PGDBHOST=aleas010
    volumes:
      - /opt/software/postgres/pgdata:/var/lib/postgresql/data
    depends_on:
      - 'postgres'
      
  postgres:
    image: 'postgres:latest'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=usersapi
      - POSTGRES_PASSWORD=dbpassword









