apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: postgres-cluster-image-policy
spec:
  repositories:
  - name: docker.io/postgres:*
    policy:
      va:
        enabled: false
